In [19]:
from fastai.vision.all import *


# Get all data

In [20]:
#print(dir(URLs))
path_mnist = untar_data(URLs.MNIST)

# Open all entries in the training set

In [21]:
train_0_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'0').ls()])
train_1_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'1').ls()])
train_2_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'2').ls()])
train_3_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'3').ls()])
train_4_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'4').ls()])
train_5_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'5').ls()])
train_6_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'6').ls()])
train_7_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'7').ls()])
train_8_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'8').ls()])
train_9_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'9').ls()])

In [22]:
train_x = (torch.cat( [train_0_tensors,
                       train_1_tensors,
                       train_2_tensors,
                       train_3_tensors,
                       train_4_tensors,
                       train_5_tensors,
                       train_6_tensors,
                       train_7_tensors,
                       train_8_tensors,
                       train_9_tensors]).float()/255).view(-1, 28*28)
train_x

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [23]:
train_y = torch.cat(  [torch.stack([tensor(1, 0, 0, 0, 0, 0, 0, 0, 0, 0)] * len(train_0_tensors)),
                       torch.stack([tensor(0, 1, 0, 0, 0, 0, 0, 0, 0, 0)] * len(train_1_tensors)),
                       torch.stack([tensor(0, 0, 1, 0, 0, 0, 0, 0, 0, 0)] * len(train_2_tensors)),
                       torch.stack([tensor(0, 0, 0, 1, 0, 0, 0, 0, 0, 0)] * len(train_3_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 1, 0, 0, 0, 0, 0)] * len(train_4_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 1, 0, 0, 0, 0)] * len(train_5_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 0, 1, 0, 0, 0)] * len(train_6_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 0, 0, 1, 0, 0)] * len(train_7_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 0, 0, 0, 1, 0)] * len(train_8_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 0, 0, 0, 0, 1)] * len(train_9_tensors))]).float()
train_y

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [24]:
train_dset = list(zip(train_x, train_y))
train_dl = DataLoader(train_dset, batch_size=256)

# Open all entries in the validation set

In [25]:
valid_0_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'0').ls()])
valid_1_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'1').ls()])
valid_2_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'2').ls()])
valid_3_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'3').ls()])
valid_4_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'4').ls()])
valid_5_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'5').ls()])
valid_6_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'6').ls()])
valid_7_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'7').ls()])
valid_8_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'8').ls()])
valid_9_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'9').ls()])

In [26]:
valid_x = (torch.cat( [valid_0_tensors,
                       valid_1_tensors,
                       valid_2_tensors,
                       valid_3_tensors,
                       valid_4_tensors,
                       valid_5_tensors,
                       valid_6_tensors,
                       valid_7_tensors,
                       valid_8_tensors,
                       valid_9_tensors]).float()/255).view(-1, 28*28)
valid_x

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [27]:
valid_y = torch.cat(  [torch.stack([tensor(1, 0, 0, 0, 0, 0, 0, 0, 0, 0)] * len(valid_0_tensors)),
                       torch.stack([tensor(0, 1, 0, 0, 0, 0, 0, 0, 0, 0)] * len(valid_1_tensors)),
                       torch.stack([tensor(0, 0, 1, 0, 0, 0, 0, 0, 0, 0)] * len(valid_2_tensors)),
                       torch.stack([tensor(0, 0, 0, 1, 0, 0, 0, 0, 0, 0)] * len(valid_3_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 1, 0, 0, 0, 0, 0)] * len(valid_4_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 1, 0, 0, 0, 0)] * len(valid_5_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 0, 1, 0, 0, 0)] * len(valid_6_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 0, 0, 1, 0, 0)] * len(valid_7_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 0, 0, 0, 1, 0)] * len(valid_8_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 0, 0, 0, 0, 1)] * len(valid_9_tensors))]).float()
valid_y

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [28]:
valid_dset = list(zip(valid_x, valid_y))
valid_dl = DataLoader(valid_dset, batch_size=256)

Define DataLoaders from the DataLoader for training data and the DataLoader from the validation data

In [29]:
digit_dls = DataLoaders(train_dl, valid_dl)

Define a loss function

In [30]:
def digit_recognition_rmse_loss(predictions, targets):
    predictions = predictions.sigmoid()
    return ((predictions-targets)**2).mean().sqrt()

Define initialization of parameters with random values

In [31]:
def init_params(size, std=1.0): return (torch.randn(size)*std).requires_grad_()



# Define a linear model

In [32]:
weights = init_params((28*28,10))
bias = init_params(10)

In [33]:
def linear1(xb): return xb@weights + bias
preds = linear1(train_x)
preds

tensor([[-25.4914,   2.0484,   1.5086,  ...,   3.7551,   4.0843, -20.9080],
        [-25.8133,  -1.8046,  -2.7907,  ...,  -4.9699,   6.9387, -12.5759],
        [-15.6790,   3.4444,  -1.0894,  ...,  -2.3538,   0.2719, -15.2585],
        ...,
        [ -7.9971, -11.8857,   4.4894,  ...,   0.5765,   4.5907, -17.0070],
        [ -8.6032,  -6.0561,  10.7553,  ...,  -1.2791,  -1.7288,  -3.7423],
        [-19.2718, -10.2326,  11.0443,  ...,  -4.7111,   3.4256,  -0.1536]],
       grad_fn=<AddBackward0>)

In [34]:
def calc_grad(xb, yb, model):
    preds = model(xb)
    loss = digit_recognition_rmse_loss(preds, yb)
    loss.backward()

In [35]:
def train_epoch(model, lr, params, dl):
    for xb,yb in dl:
        calc_grad(xb, yb, model)
        for p in params:
            p.data -= p.grad*lr
            p.grad.zero_()

In [36]:
def batch_accuracy(xb, yb):
    preds = xb.sigmoid()
    pred_labels = preds.argmax(dim=1)
    true_labels = yb.argmax(dim=1)
    return (pred_labels == true_labels).float().mean()

In [37]:
def validate_epoch(model):
    accs = [batch_accuracy(model(xb), yb) for xb,yb in valid_dl]
    return round(torch.stack(accs).mean().item(), 4)

In [38]:
lr = 1.
params = weights,bias
train_epoch(linear1, lr, params, train_dl)
validate_epoch(linear1)

0.2119

In [39]:
for i in range(150):
    train_epoch(linear1, lr, params, train_dl)
    print(f'Epoch {i} accuracy: {validate_epoch(linear1)}')

Epoch 0 accuracy: 0.2715
Epoch 1 accuracy: 0.3226
Epoch 2 accuracy: 0.3651
Epoch 3 accuracy: 0.3886
Epoch 4 accuracy: 0.408
Epoch 5 accuracy: 0.4203
Epoch 6 accuracy: 0.4266
Epoch 7 accuracy: 0.4311
Epoch 8 accuracy: 0.4388
Epoch 9 accuracy: 0.444
Epoch 10 accuracy: 0.4476
Epoch 11 accuracy: 0.45
Epoch 12 accuracy: 0.4553
Epoch 13 accuracy: 0.4563
Epoch 14 accuracy: 0.4591
Epoch 15 accuracy: 0.4604
Epoch 16 accuracy: 0.4614
Epoch 17 accuracy: 0.4633
Epoch 18 accuracy: 0.4649
Epoch 19 accuracy: 0.4662
Epoch 20 accuracy: 0.4679
Epoch 21 accuracy: 0.4694
Epoch 22 accuracy: 0.4706
Epoch 23 accuracy: 0.4721
Epoch 24 accuracy: 0.4727
Epoch 25 accuracy: 0.4738
Epoch 26 accuracy: 0.4745
Epoch 27 accuracy: 0.475
Epoch 28 accuracy: 0.4755
Epoch 29 accuracy: 0.476
Epoch 30 accuracy: 0.477
Epoch 31 accuracy: 0.4772
Epoch 32 accuracy: 0.4777
Epoch 33 accuracy: 0.4788
Epoch 34 accuracy: 0.4793
Epoch 35 accuracy: 0.4799
Epoch 36 accuracy: 0.4805
Epoch 37 accuracy: 0.4818
Epoch 38 accuracy: 0.4831
Epo