In [5]:
from fastai.vision.all import *


# Get all data

In [46]:
#print(dir(URLs))
path_mnist = untar_data(URLs.MNIST)

# Open all entries in the training set

In [9]:
train_0_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'0').ls()])
train_1_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'1').ls()])
train_2_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'2').ls()])
train_3_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'3').ls()])
train_4_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'4').ls()])
train_5_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'5').ls()])
train_6_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'6').ls()])
train_7_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'7').ls()])
train_8_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'8').ls()])
train_9_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'training'/'9').ls()])

In [10]:
train_x = (torch.cat( [train_0_tensors,
                       train_1_tensors,
                       train_2_tensors,
                       train_3_tensors,
                       train_4_tensors,
                       train_5_tensors,
                       train_6_tensors,
                       train_7_tensors,
                       train_8_tensors,
                       train_9_tensors]).float()/255).view(-1, 28*28)
train_x

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [11]:
train_y = torch.cat(  [torch.stack([tensor(1, 0, 0, 0, 0, 0, 0, 0, 0, 0)] * len(train_0_tensors)),
                       torch.stack([tensor(0, 1, 0, 0, 0, 0, 0, 0, 0, 0)] * len(train_1_tensors)),
                       torch.stack([tensor(0, 0, 1, 0, 0, 0, 0, 0, 0, 0)] * len(train_2_tensors)),
                       torch.stack([tensor(0, 0, 0, 1, 0, 0, 0, 0, 0, 0)] * len(train_3_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 1, 0, 0, 0, 0, 0)] * len(train_4_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 1, 0, 0, 0, 0)] * len(train_5_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 0, 1, 0, 0, 0)] * len(train_6_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 0, 0, 1, 0, 0)] * len(train_7_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 0, 0, 0, 1, 0)] * len(train_8_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 0, 0, 0, 0, 1)] * len(train_9_tensors))]).float()
train_y

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [12]:
train_dset = list(zip(train_x, train_y))
train_dl = DataLoader(train_dset, batch_size=256)

# Open all entries in the validation set

In [13]:
valid_0_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'0').ls()])
valid_1_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'1').ls()])
valid_2_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'2').ls()])
valid_3_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'3').ls()])
valid_4_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'4').ls()])
valid_5_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'5').ls()])
valid_6_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'6').ls()])
valid_7_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'7').ls()])
valid_8_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'8').ls()])
valid_9_tensors = torch.stack([tensor(Image.open(o)) for o in (path_mnist/'testing'/'9').ls()])

In [14]:
valid_x = (torch.cat( [valid_0_tensors,
                       valid_1_tensors,
                       valid_2_tensors,
                       valid_3_tensors,
                       valid_4_tensors,
                       valid_5_tensors,
                       valid_6_tensors,
                       valid_7_tensors,
                       valid_8_tensors,
                       valid_9_tensors]).float()/255).view(-1, 28*28)
valid_x

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [15]:
valid_y = torch.cat(  [torch.stack([tensor(1, 0, 0, 0, 0, 0, 0, 0, 0, 0)] * len(valid_0_tensors)),
                       torch.stack([tensor(0, 1, 0, 0, 0, 0, 0, 0, 0, 0)] * len(valid_1_tensors)),
                       torch.stack([tensor(0, 0, 1, 0, 0, 0, 0, 0, 0, 0)] * len(valid_2_tensors)),
                       torch.stack([tensor(0, 0, 0, 1, 0, 0, 0, 0, 0, 0)] * len(valid_3_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 1, 0, 0, 0, 0, 0)] * len(valid_4_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 1, 0, 0, 0, 0)] * len(valid_5_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 0, 1, 0, 0, 0)] * len(valid_6_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 0, 0, 1, 0, 0)] * len(valid_7_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 0, 0, 0, 1, 0)] * len(valid_8_tensors)),
                       torch.stack([tensor(0, 0, 0, 0, 0, 0, 0, 0, 0, 1)] * len(valid_9_tensors))]).float()
valid_y

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        [1., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [16]:
valid_dset = list(zip(valid_x, valid_y))
valid_dl = DataLoader(valid_dset, batch_size=256)

Define DataLoaders from the DataLoader for training data and the DataLoader from the validation data

In [ ]:
digit_dls = DataLoaders(train_dl, valid_dl)

Define a loss function

In [23]:
def digit_recognition_rmse_loss(predictions, targets):
    predictions = predictions.sigmoid()
    return ((predictions-targets)**2).mean().sqrt()

Define initialization of parameters with random values

In [19]:
def init_params(size, std=1.0): return (torch.randn(size)*std).requires_grad_()



# Define a linear model

In [21]:
weights = init_params((28*28,10))
bias = init_params(10)

In [20]:
def linear1(xb): return xb@weights + bias
preds = linear1(train_x)
preds

tensor([[ -5.4191, -18.7961,   4.2408,  ...,   1.0790,  -9.4976,  -9.8761],
        [ -2.3162, -21.6028,   6.0779,  ...,  -0.5465, -14.8792,   1.9873],
        [ -3.5054, -17.6888,  -0.1479,  ..., -13.1764,   1.3012,   4.2527],
        ...,
        [ -6.6577,   1.5923,   2.0058,  ...,  -2.7113,  -3.4279,   3.9862],
        [  5.2012,   0.7095,   4.3216,  ...,  -3.5041,   4.8373,  -6.3017],
        [ -3.4438,   2.4411, -10.2611,  ...,  -6.2664,   6.0397,  -7.7298]],
       grad_fn=<AddBackward0>)

In [24]:
def calc_grad(xb, yb, model):
    preds = model(xb)
    loss = digit_recognition_rmse_loss(preds, yb)
    loss.backward()

In [30]:
def train_epoch(model, lr, params, dl):
    for xb,yb in dl:
        calc_grad(xb, yb, model)
        for p in params:
            p.data -= p.grad*lr
            p.grad.zero_()

In [26]:
def batch_accuracy(xb, yb):
    preds = xb.sigmoid()
    pred_labels = preds.argmax(dim=1)
    true_labels = yb.argmax(dim=1)
    return (pred_labels == true_labels).float().mean()

In [27]:
def validate_epoch(model):
    accs = [batch_accuracy(model(xb), yb) for xb,yb in valid_dl]
    return round(torch.stack(accs).mean().item(), 4)

In [39]:
lr = 1.
params = weights,bias
train_epoch(linear1, lr, params, train_dl)
validate_epoch(linear1)

0.5466

In [45]:
for i in range(150):
    train_epoch(linear1, lr, params, train_dl)
    print(f'Epoch {i} accuracy: {validate_epoch(linear1)}')

Epoch 0 accuracy: 0.6273
Epoch 1 accuracy: 0.628
Epoch 2 accuracy: 0.6286
Epoch 3 accuracy: 0.6292
Epoch 4 accuracy: 0.6298
Epoch 5 accuracy: 0.6301
Epoch 6 accuracy: 0.6301
Epoch 7 accuracy: 0.6309
Epoch 8 accuracy: 0.6314
Epoch 9 accuracy: 0.6319
Epoch 10 accuracy: 0.6323
Epoch 11 accuracy: 0.6324
Epoch 12 accuracy: 0.6327
Epoch 13 accuracy: 0.6329
Epoch 14 accuracy: 0.6334
Epoch 15 accuracy: 0.6339
Epoch 16 accuracy: 0.6342
Epoch 17 accuracy: 0.6347
Epoch 18 accuracy: 0.6348
Epoch 19 accuracy: 0.6351
Epoch 20 accuracy: 0.6354
Epoch 21 accuracy: 0.6359
Epoch 22 accuracy: 0.6362
Epoch 23 accuracy: 0.6367
Epoch 24 accuracy: 0.6368
Epoch 25 accuracy: 0.637
Epoch 26 accuracy: 0.6373
Epoch 27 accuracy: 0.6375
Epoch 28 accuracy: 0.6379
Epoch 29 accuracy: 0.6381
